#pragma once

#include <array>

#include "util/types.hh"

namespace treyarch { namespace amalga {
    enum e_resource_type : u32 {
        error = 0,
        descriptor,
        sin,
        textfile,
        terrain_types,
        language,
        district_graph,
        speedtree_coll,
        speedtree_coll_refs,
        script,
        script_gv,
        script_sv,
        GenBlockMap,
        traffic_light_info,
        texture,
        fxbinary,
        material,
        mesh,
        ngl_skeleton,
        nal_skeleton,
        ngl_font,
        animation,
        scene_animation,
        morph,
        efx,
        merged_apk,
        nal_skeleton_map,
        convex_hull_mesh,
        vehicle_model_depot,
        TILEMAP,
        ENVIRONMENT,
        LIGHTBEHAVIOR,
        GRAPHICSOPTIONS,
        EFFECTCONTAINER,
        SMDECALMATERIAL,
        PHATPALETTE,
        COWBELL,
        MESHMAP,
        CLOUDTWEAK,
        CITYLODS,
        SMROADPARAM,
        ALLBUILDINGS,
        UIP3DW,
        UIP3DT,
        SMDECALPARAM,
        ADJUSTMENTLAYERSLIBRARY,
        OUTDOORS,
        DAYSKYCOLOR,
        NIGHTSKYCOLOR,
        PRELIGHT,
        SMBUILDINGLODPARAM,
        SMROADLODPARAM,
        SMRETROFITPARAM,
        JSON_REGIONINFO,
        JSON_METERDATA,
        JSON_METERBEHAVIOR,
        JSON_COMBOMOVEINFO,
        JSON_QUESTDESC,
        JSON_QUESTLIST,
        JSON_CONVERSATION,
        JSON_SPAWNTABLE,
        JSON_SPAWNPROGRESSION,
        JSON_SPAWNPOINTS,
        JSON_NEIGHBORHOODINFO,
        JSON_DEF_VALUES,
        JSON_PROGRESSMESSAGES,
        JSON_SPAWNITEMS,
        JSON_UPGRADES,
        JSON_SOUNDMAP,
        JSON_UICHARINFO,
        JSON_SUMMONPROGRESSION,
        JSON_ENVIRONMENTPROGRESSION,
        JSON_RENDERLOD,
        viseme_stream,
        static_colgeom,
        lego_map,
        scn_quad_path,
        path,
        scn_env_box,
        cosmetic_environ,
        sm3_light,
        stall,
        slim,
        slim_list,
        als_file,
        ai_state_graph,
        base_ai,
        scn_audio_box,
        box_trigger_info,
        scn_entity,
        anchor_coll,
        fx_cache,
        entity,
        cut_scene,
        collision_mesh,
        packfile,
        speedtree_spt,
        speedtree_seed,
        speedtree_wind,
        sound_toc,
        sound_index,
        ise_library,
        vertex_shader,
        pixel_shader,
        count,
    };

    struct resource_type {
        e_resource_type type;
        const char* desc;
        const char* desc_plural;
        const char* ext;
        const char* path;
        const char* resource_handler_class;
    };

    inline constexpr std::array<resource_type, 104> resource_types = {{
        {
            e_resource_type::error,
            "error",
            "error",
            ".NONE",
            "",
            "empty_resource_handler"
        },
        {
            e_resource_type::descriptor,
            "descriptor",
            "descriptors",
            ".DESC",
            "DESC\\",
            "mashable_resource_handler<class_level_descriptor_set>"
        },
        {
            e_resource_type::sin,
            "sin",
            "sins",
            ".SIN",
            "SIN\\",
            "mashable_resource_handler<class_sin_container>"
        },
        {
            e_resource_type::textfile,
            "textfile",
            "textfiles",
            ".TXT",
            "TXT\\",
            "mashable_resource_handler<struct_text_resource>"
        },
        {
            e_resource_type::terrain_types,
            "terrain_types",
            "terrain_typeses",
            ".CSV",
            "CSV\\",
            "mashable_resource_handler<struct_terrain_types_set>"
        },
        {
            e_resource_type::language,
            "language",
            "languages",
            ".LANG",
            "LANG\\",
            "mashable_resource_handler<class_localized_string_table>"
        },
        {
            e_resource_type::district_graph,
            "district_graph",
            "district_graphs",
            ".DSG",
            "DSG\\",
            "mashable_resource_handler<class_district_graph_container>"
        },
        {
            e_resource_type::speedtree_coll,
            "speedtree_coll",
            "speedtree_colls",
            ".STC",
            "STC\\",
            "mashable_resource_handler<class_speedtree_collection>"
        },
        {
            e_resource_type::speedtree_coll_refs,
            "speedtree_coll_refs",
            "speedtree_coll_refss",
            ".PCSTCR",
            "PCSTCR\\",
            "mashable_resource_handler<class_speedtree_collection_reference>"
        },
        {
            e_resource_type::script,
            "script",
            "scripts",
            ".PCSX",
            "PCSX\\",
            "mashable_resource_handler<class_script_executable>"
        },
        {
            e_resource_type::script_gv,
            "script_gv",
            "script_gvs",
            ".PCGV",
            "PCGV\\",
            "mashable_resource_handler<class_script_var_container>"
        },
        {
            e_resource_type::script_sv,
            "script_sv",
            "script_svs",
            ".PCSV",
            "PCSV\\",
            "mashable_resource_handler<class_script_var_container>"
        },
        {
            e_resource_type::GenBlockMap,
            "GenBlockMap",
            "GenBlockMaps",
            ".GBMAP",
            "GBMAP\\",
            "mashable_resource_handler<class_gb_map>"
        },
        {
            e_resource_type::traffic_light_info,
            "traffic_light_info",
            "traffic_light_infos",
            ".TRAF_LT_INFPC",
            "TRAF_LT_INFPC\\",
            "mashable_resource_handler<class_region_traffic_light_info>"
        },
        {
            e_resource_type::texture,
            "texture",
            "textures",
            ".PCTEXTURE",
            "PCTEXTURE\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::fxbinary,
            "fxbinary",
            "fxbinaries",
            ".PCFX",
            "PCFX\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::material,
            "material",
            "materials",
            ".PCMATERIAL",
            "PCMATERIAL\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::mesh,
            "mesh",
            "meshes",
            ".PCMESH",
            "PCMESH\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::ngl_skeleton,
            "ngl_skeleton",
            "ngl_skeletons",
            ".PCNGLSKELETON",
            "PCNGLSKELETON\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::nal_skeleton,
            "nal_skeleton",
            "nal_skeletons",
            ".PCSKEL",
            "PCSKEL\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::ngl_font,
            "ngl_font",
            "ngl_fonts",
            ".PCFONT",
            "PCFONT\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::animation,
            "animation",
            "animations",
            ".PCANIM",
            "PCANIM\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::scene_animation,
            "scene_animation",
            "scene_animations",
            ".PCSANIM",
            "PCSANIM\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::morph,
            "morph",
            "morphs",
            ".PCMORPH",
            "PCMORPH\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::efx,
            "efx",
            "efxs",
            ".PCEFXB",
            "PCEFXB\\",
            "merged_singular_apk_resource_handler"
        },
        {
            e_resource_type::merged_apk,
            "merged_apk",
            "merged_apks",
            ".PCAPK",
            "PCAPK\\",
            "merged_apk_resource_handler"
        },
        {
            e_resource_type::nal_skeleton_map,
            "nal_skeleton_map",
            "nal_skeleton_maps",
            ".SKELMAP",
            "SKELMAP\\",
            "singular_apk_resource_handler"
        },
        {
            e_resource_type::convex_hull_mesh,
            "convex_hull_mesh",
            "convex_hull_meshes",
            ".PCCVX",
            "PCCVX\\",
            "singular_apk_resource_handler"
        },
        {
            e_resource_type::vehicle_model_depot,
            "vehicle_model_depot",
            "vehicle_model_depots",
            ".VDEPOT",
            "VDEPOT\\",
            "mashable_resource_handler<class_vehicle_model_depot>"
        },
        {
            e_resource_type::TILEMAP,
            "TILEMAP",
            "TILEMAPs",
            ".TILEMAP",
            "TILEMAP\\",
            "mashable_resource_handler<class_Tilemap>"
        },
        {
            e_resource_type::ENVIRONMENT,
            "ENVIRONMENT",
            "ENVIRONMENTs",
            ".ENVIRONMENT",
            "ENVIRONMENT\\",
            "mashable_resource_handler<class_Environment>"
        },
        {
            e_resource_type::LIGHTBEHAVIOR,
            "LIGHTBEHAVIOR",
            "LIGHTBEHAVIORs",
            ".LIGHTBEHAVIOR",
            "LIGHTBEHAVIOR\\",
            "mashable_resource_handler<class_LightBehavior>"
        },
        {
            e_resource_type::GRAPHICSOPTIONS,
            "GRAPHICSOPTIONS",
            "GRAPHICSOPTIONSs",
            ".GRAPHICSOPTIONS",
            "GRAPHICSOPTIONS\\",
            "mashable_resource_handler<class_GraphicsOptions>"
        },
        {
            e_resource_type::EFFECTCONTAINER,
            "EFFECTCONTAINER",
            "EFFECTCONTAINERs",
            ".EFFECTCONTAINER",
            "EFFECTCONTAINER\\",
            "mashable_resource_handler<class_EffectContainer>"
        },
        {
            e_resource_type::SMDECALMATERIAL,
            "SMDECALMATERIAL",
            "SMDECALMATERIALs",
            ".SMDECALMATERIAL",
            "SMDECALMATERIAL\\",
            "mashable_resource_handler<class_SMDecalMaterial>"
        },
        {
            e_resource_type::PHATPALETTE,
            "PHATPALETTE",
            "PHATPALETTEs",
            ".PHATPALETTE",
            "PHATPALETTE\\",
            "mashable_resource_handler<class_PhatPalette>"
        },
        {
            e_resource_type::COWBELL,
            "COWBELL",
            "COWBELLs",
            ".COWBELL",
            "COWBELL\\",
            "mashable_resource_handler<class_CowbellFile>"
        },
        {
            e_resource_type::MESHMAP,
            "MESHMAP",
            "MESHMAPs",
            ".MESHMAP",
            "MESHMAP\\",
            "mashable_resource_handler<class_Meshmap>"
        },
        {
            e_resource_type::CLOUDTWEAK,
            "CLOUDTWEAK",
            "CLOUDTWEAKs",
            ".CLOUDTWEAK",
            "CLOUDTWEAK\\",
            "mashable_resource_handler<class_CloudTweak>"
        },
        {
            e_resource_type::CITYLODS,
            "CITYLODS",
            "CITYLODSs",
            ".CITYLODS",
            "CITYLODS\\",
            "mashable_resource_handler<class_CityLODs>"
        },
        {
            e_resource_type::SMROADPARAM,
            "SMROADPARAM",
            "SMROADPARAMs",
            ".SMROADPARAM",
            "SMROADPARAM\\",
            "mashable_resource_handler<class_SMRoadParam>"
        },
        {
            e_resource_type::ALLBUILDINGS,
            "ALLBUILDINGS",
            "ALLBUILDINGSs",
            ".ALLBUILDINGS",
            "ALLBUILDINGS\\",
            "mashable_resource_handler<class_AllBuildings>"
        },
        {
            e_resource_type::UIP3DW,
            "UIP3DW",
            "UIP3DWs",
            ".UIP3DW",
            "UIP3DW\\",
            "mashable_resource_handler<class_IGO3DWidgetParameters>"
        },
        {
            e_resource_type::UIP3DT,
            "UIP3DT",
            "UIP3DTs",
            ".UIP3DT",
            "UIP3DT\\",
            "mashable_resource_handler<class_IGO3DTextParameters>"
        },
        {
            e_resource_type::SMDECALPARAM,
            "SMDECALPARAM",
            "SMDECALPARAMs",
            ".SMDECALPARAM",
            "SMDECALPARAM\\",
            "mashable_resource_handler<class_SMDecalParam>"
        },
        {
            e_resource_type::ADJUSTMENTLAYERSLIBRARY,
            "ADJUSTMENTLAYERSLIBRARY",
            "ADJUSTMENTLAYERSLIBRARYs",
            ".ADJUSTMENTLAYERSLIBRARY",
            "ADJUSTMENTLAYERSLIBRARY\\",
            "mashable_resource_handler<class_AdjustmentLayersLibrary>"
        },
        {
            e_resource_type::OUTDOORS,
            "OUTDOORS",
            "OUTDOORSs",
            ".OUTDOORS",
            "OUTDOORS\\",
            "mashable_resource_handler<class_Outdoors>"
        },
        {
            e_resource_type::DAYSKYCOLOR,
            "DAYSKYCOLOR",
            "DAYSKYCOLORs",
            ".DAYSKYCOLOR",
            "DAYSKYCOLOR\\",
            "mashable_resource_handler<class_daySkyColor>"
        },
        {
            e_resource_type::NIGHTSKYCOLOR,
            "NIGHTSKYCOLOR",
            "NIGHTSKYCOLORs",
            ".NIGHTSKYCOLOR",
            "NIGHTSKYCOLOR\\",
            "mashable_resource_handler<class_nightSkyColor>"
        },
        {
            e_resource_type::PRELIGHT,
            "PRELIGHT",
            "PRELIGHTs",
            ".PRELIGHT",
            "PRELIGHT\\",
            "mashable_resource_handler<class_PreLight>"
        },
        {
            e_resource_type::SMBUILDINGLODPARAM,
            "SMBUILDINGLODPARAM",
            "SMBUILDINGLODPARAMs",
            ".SMBUILDINGLODPARAM",
            "SMBUILDINGLODPARAM\\",
            "mashable_resource_handler<class_SMBuildingLODParam>"
        },
        {
            e_resource_type::SMROADLODPARAM,
            "SMROADLODPARAM",
            "SMROADLODPARAMs",
            ".SMROADLODPARAM",
            "SMROADLODPARAM\\",
            "mashable_resource_handler<class_SMRoadLODParam>"
        },
        {
            e_resource_type::SMRETROFITPARAM,
            "SMRETROFITPARAM",
            "SMRETROFITPARAMs",
            ".SMRETROFITPARAM",
            "SMRETROFITPARAM\\",
            "mashable_resource_handler<class_SMRetrofitParam>"
        },
        {
            e_resource_type::JSON_REGIONINFO,
            "JSON_REGIONINFO",
            "JSON_REGIONINFOs",
            ".JSON_REGIONINFO",
            "JSON_REGIONINFO\\",
            "mashable_resource_handler<class_region_spawn_interface>"
        },
        {
            e_resource_type::JSON_METERDATA,
            "JSON_METERDATA",
            "JSON_METERDATAs",
            ".JSON_METERDATA",
            "JSON_METERDATA\\",
            "mashable_resource_handler<class_meter_data_file>"
        },
        {
            e_resource_type::JSON_METERBEHAVIOR,
            "JSON_METERBEHAVIOR",
            "JSON_METERBEHAVIORs",
            ".JSON_METERBEHAVIOR",
            "JSON_METERBEHAVIOR\\",
            "mashable_resource_handler<class_meter_behavior_file>"
        },
        {
            e_resource_type::JSON_COMBOMOVEINFO,
            "JSON_COMBOMOVEINFO",
            "JSON_COMBOMOVEINFOs",
            ".JSON_COMBOMOVEINFO",
            "JSON_COMBOMOVEINFO\\",
            "mashable_resource_handler<class_combo_move_type_file>"
        },
        {
            e_resource_type::JSON_QUESTDESC,
            "JSON_QUESTDESC",
            "JSON_QUESTDESCs",
            ".JSON_QUESTDESC",
            "JSON_QUESTDESC\\",
            "mashable_resource_handler<class_quest_descriptions>"
        },
        {
            e_resource_type::JSON_QUESTLIST,
            "JSON_QUESTLIST",
            "JSON_QUESTLISTs",
            ".JSON_QUESTLIST",
            "JSON_QUESTLIST\\",
            "mashable_resource_handler<class_quest_list>"
        },
        {
            e_resource_type::JSON_CONVERSATION,
            "JSON_CONVERSATION",
            "JSON_CONVERSATIONs",
            ".JSON_CONVERSATION",
            "JSON_CONVERSATION\\",
            "mashable_resource_handler<class_conversation>"
        },
        {
            e_resource_type::JSON_SPAWNTABLE,
            "JSON_SPAWNTABLE",
            "JSON_SPAWNTABLEs",
            ".JSON_SPAWNTABLE",
            "JSON_SPAWNTABLE\\",
            "mashable_resource_handler<class_spawn_table_interface>"
        },
        {
            e_resource_type::JSON_SPAWNPROGRESSION,
            "JSON_SPAWNPROGRESSION",
            "JSON_SPAWNPROGRESSIONs",
            ".JSON_SPAWNPROGRESSION",
            "JSON_SPAWNPROGRESSION\\",
            "mashable_resource_handler<class_spawn_item_collection>"
        },
        {
            e_resource_type::JSON_SPAWNPOINTS,
            "JSON_SPAWNPOINTS",
            "JSON_SPAWNPOINTSs",
            ".JSON_SPAWNPOINTS",
            "JSON_SPAWNPOINTS\\",
            "mashable_resource_handler<class_spawn_point_list_collection>"
        },
        {
            e_resource_type::JSON_NEIGHBORHOODINFO,
            "JSON_NEIGHBORHOODINFO",
            "JSON_NEIGHBORHOODINFOs",
            ".JSON_NEIGHBORHOODINFO",
            "JSON_NEIGHBORHOODINFO\\",
            "mashable_resource_handler<class_neighborhood_interface>"
        },
        {
            e_resource_type::JSON_DEF_VALUES,
            "JSON_DEF_VALUES",
            "JSON_DEF_VALUESs",
            ".JSON_DEF_VALUES",
            "JSON_DEF_VALUES\\",
            "mashable_resource_handler<class_default_values>"
        },
        {
            e_resource_type::JSON_PROGRESSMESSAGES,
            "JSON_PROGRESSMESSAGES",
            "JSON_PROGRESSMESSAGESs",
            ".JSON_PROGRESSMESSAGES",
            "JSON_PROGRESSMESSAGES\\",
            "mashable_resource_handler<class_progression_messages>"
        },
        {
            e_resource_type::JSON_SPAWNITEMS,
            "JSON_SPAWNITEMS",
            "JSON_SPAWNITEMSs",
            ".JSON_SPAWNITEMS",
            "JSON_SPAWNITEMS\\",
            "mashable_resource_handler<class_static_spawn_item_collection>"
        },
        {
            e_resource_type::JSON_UPGRADES,
            "JSON_UPGRADES",
            "JSON_UPGRADESs",
            ".JSON_UPGRADES",
            "JSON_UPGRADES\\",
            "mashable_resource_handler<class_rpg_upgrades>"
        },
        {
            e_resource_type::JSON_SOUNDMAP,
            "JSON_SOUNDMAP",
            "JSON_SOUNDMAPs",
            ".JSON_SOUNDMAP",
            "JSON_SOUNDMAP\\",
            "mashable_resource_handler<class_sound_map>"
        },
        {
            e_resource_type::JSON_UICHARINFO,
            "JSON_UICHARINFO",
            "JSON_UICHARINFOs",
            ".JSON_UICHARINFO",
            "JSON_UICHARINFO\\",
            "mashable_resource_handler<class_ui_character_info_list>"
        },
        {
            e_resource_type::JSON_SUMMONPROGRESSION,
            "JSON_SUMMONPROGRESSION",
            "JSON_SUMMONPROGRESSIONs",
            ".JSON_SUMMONPROGRESSION",
            "JSON_SUMMONPROGRESSION\\",
            "mashable_resource_handler<class_summon_progression>"
        },
        {
            e_resource_type::JSON_ENVIRONMENTPROGRESSION,
            "JSON_ENVIRONMENTPROGRESSION",
            "JSON_ENVIRONMENTPROGRESSIONs",
            ".JSON_ENVIRONMENTPROGRESSION",
            "JSON_ENVIRONMENTPROGRESSION\\",
            "mashable_resource_handler<class_environment_progression>"
        },
        {
            e_resource_type::JSON_RENDERLOD,
            "JSON_RENDERLOD",
            "JSON_RENDERLODs",
            ".JSON_RENDERLOD",
            "JSON_RENDERLOD\\",
            "mashable_resource_handler<class_render_lod_mgr>"
        },
        {
            e_resource_type::viseme_stream,
            "viseme_stream",
            "viseme_streams",
            ".LIP",
            "LIP\\",
            "mashable_resource_handler<class_VisemeStream>"
        },
        {
            e_resource_type::static_colgeom,
            "static_colgeom",
            "static_colgeoms",
            ".SCGPC",
            "SCGPC\\",
            "mashable_resource_handler<class_static_colgeom_root>"
        },
        {
            e_resource_type::lego_map,
            "lego_map",
            "lego_maps",
            ".LEGO_MAPPC",
            "LEGO_MAPPC\\",
            "mashable_resource_handler<struct_lego_map_root_node>"
        },
        {
            e_resource_type::scn_quad_path,
            "scn_quad_path",
            "scn_quad_paths",
            ".QP",
            "QP\\",
            "mashable_resource_handler<class_ai_pf_region_graph>"
        },
        {
            e_resource_type::path,
            "path",
            "path",
            ".PATH",
            "PATH\\",
            "mashable_resource_handler<class_path_graph>"
        },
        {
            e_resource_type::scn_env_box,
            "scn_env_box",
            "scn_env_boxes",
            ".EB",
            "EB\\",
            "mashable_resource_handler<class_environment_box_set>"
        },
        {
            e_resource_type::cosmetic_environ,
            "cosmetic_environ",
            "cosmetic_environs",
            ".CE",
            "CE\\",
            "mashable_resource_handler<class_cosmetic_environments_set>"
        },
        {
            e_resource_type::sm3_light,
            "sm3_light",
            "sm3_lights",
            ".SM3_LIGHTPC",
            "SM3_LIGHTPC\\",
            "mashable_resource_handler<class_sm3_light>"
        },
        {
            e_resource_type::stall,
            "stall",
            "stalls",
            ".STALL",
            "STALL\\",
            "stall_resource_handler"
        },
        {
            e_resource_type::slim,
            "slim",
            "slims",
            ".SLIM",
            "SLIM\\",
            "empty_resource_handler"
        },
        {
            e_resource_type::slim_list,
            "slim_list",
            "slim_lists",
            ".SLIMLIST",
            "SLIMLIST\\",
            "slim_list_handler"
        },
        {
            e_resource_type::als_file,
            "als_file",
            "als_files",
            ".ALS",
            "ALS\\",
            "mashable_resource_handler<class_als::animation_logic_system_shared>"
        },
        {
            e_resource_type::ai_state_graph,
            "ai_state_graph",
            "ai_state_graphs",
            ".ASG",
            "ASG\\",
            "mashable_resource_handler<class_state_graph>"
        },
        {
            e_resource_type::base_ai,
            "base_ai",
            "base_ais",
            ".BAI",
            "BAI\\",
            "mashable_resource_handler<class_core_ai_resource>"
        },
        {
            e_resource_type::scn_audio_box,
            "scn_audio_box",
            "scn_audio_boxes",
            ".AB",
            "AB\\",
            "mashable_resource_handler<class_region_audio_box_set>"
        },
        {
            e_resource_type::box_trigger_info,
            "box_trigger_info",
            "box_trigger_infos",
            ".BOX_TRIG_INFPC",
            "BOX_TRIG_INFPC\\",
            "box_trigger_resource_handler"
        },
        {
            e_resource_type::scn_entity,
            "scn_entity",
            "scn_entities",
            ".ENS",
            "ENS\\",
            "scene_entity_container_resource_handler"
        },
        {
            e_resource_type::anchor_coll,
            "anchor_coll",
            "anchor_colls",
            ".PCAC",
            "PCAC\\",
            "anchor_collection_resource_handler"
        },
        {
            e_resource_type::fx_cache,
            "fx_cache",
            "fx_caches",
            ".FX_CACHE",
            "FX_CACHE\\",
            "mashable_resource_handler<class_fx_cache>"
        },
        {
            e_resource_type::entity,
            "entity",
            "entities",
            ".ENT",
            "ENT\\",
            "empty_resource_handler"
        },
        {
            e_resource_type::cut_scene,
            "cut_scene",
            "cut_scenes",
            ".CUT",
            "CUT\\",
            "mashable_resource_handler<class_cut_scene>"
        },
        {
            e_resource_type::collision_mesh,
            "collision_mesh",
            "collision_meshes",
            ".COLL",
            "COLL\\",
            "empty_resource_handler"
        },
        {
            e_resource_type::packfile,
            "packfile",
            "packfiles",
            ".PCPACK",
            "PCPACK\\",
            "empty_resource_handler"
        },
        {
            e_resource_type::speedtree_spt,
            "speedtree_spt",
            "speedtree_spts",
            ".SPT",
            "SPT\\",
            "empty_resource_handler"
        },
        {
            e_resource_type::speedtree_seed,
            "speedtree_seed",
            "speedtree_seeds",
            ".SEED",
            "SEED\\",
            "empty_resource_handler"
        },
        {
            e_resource_type::speedtree_wind,
            "speedtree_wind",
            "speedtree_winds",
            ".WIND",
            "WIND\\",
            "empty_resource_handler"
        },
        {
            e_resource_type::sound_toc,
            "sound_toc",
            "sound_tocs",
            ".pcstoc",
            "pcstoc\\",
            "mashable_resource_handler<class_sound_toc>"
        },
        {
            e_resource_type::sound_index,
            "sound_index",
            "sound_indexs",
            ".sndids",
            "sndids\\",
            "mashable_resource_handler<class_sound_index>"
        },
        {
            e_resource_type::ise_library,
            "ise_library",
            "ise_libraries",
            ".json_ise",
            "json_ise\\",
            "ise_library_handler"
        },
        {
            e_resource_type::vertex_shader,
            "vertex_shader",
            "vertex_shaders",
            ".PCVS",
            "PCVS\\",
            "vertex_shader_handler"
        },
        {
            e_resource_type::pixel_shader,
            "pixel_shader",
            "pixel_shaders",
            ".PCPS",
            "PCPS\\",
            "pixel_shader_handler"
        },
    }};
}} // treyarch::amalga